# Author: Steven Yi
# Time spent: 30 minutes

spring:
  application:
    name: Swipe4MeBackend
  config:
    import: optional:file:.env[.properties]
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  servlet:
    context-path: /api

logging:
  level:
    org.springframework: DEBUG
    org.apache.coyote.http11.Http11InputBuffer: TRACE
    com.sp25group8: DEBUG

swipe4me:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000
