spring:
  application:
    name: Swipe4MeBackend
  config:
    import: optional:file:.env[.properties]
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5432}/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}

server:
  servlet:
    context-path: /api

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: TRACE
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG
