services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: secret
      TZ: UTC
    volumes:
      - swipe4me-pg-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  swipe4me-pg-local: